name: hrm_app
description: A complete Flutter HRM Employee Attendance Application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Navigation
  go_router: ^13.2.0
  
  # Networking
  dio: ^5.4.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # UI & Styling
  google_fonts: ^6.2.1
  intl: ^0.20.3
  
  # Camera & ML
  camera: ^0.10.5+9
  google_mlkit_face_detection: ^0.10.0
  
  # Permissions
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
